name: Run recusfiscaux (main.py)

on:
  workflow_dispatch:
    inputs:
      extra_args:
        description: "Arguments optionnels pour main.py"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OS packages (Tkinter + virtual display)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-tk tk xvfb
          python3 -V
          pip3 -V

      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Ensure output folder exists
        run: mkdir -p resultats

      - name: Run main.py (headless via Xvfb)
        run: xvfb-run -a python3 main.py ${{ github.event.inputs.extra_args }}

      - name: List outputs
        run: |
          echo "Contenu de resultats :"
          ls -la resultats || true

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: recusfiscaux-resultats
          path: resultats/**
          if-no-files-found: warn
          retention-days: 7